theme: jekyll-theme-minimal
show_downloads: ["true"]
logo: /assets/imgs/logo.png
title: CONAN
tsdllogo: /assets/imgs/horizontalLightBrackgrounds.png

navigation:
  - title: Video
    link: /video.hmtl
